### PR TITLE
Add forward icon

### PR DESCRIPTION
**Pull request by mperrotti**

### CODE REVIEW

**Review by akdetrick — APPROVED** [review]

**Review by akdetrick — CHANGES_REQUESTED** [review]
What's the difference between `forward`, `arrow-right`, and `chevron-right`?

**Comment by akdetrick** [comment]
Should it be `invite`?

**Comment by mperrotti** [comment]
Agreed with @akdetrick - changing to "invite"

**Comment by akdetrick** [comment]
looks like the artboard names didn't change - seeing `forward` svg files being generated...

**Comment by mperrotti** [comment]
@akdetrick - artboards say `invite` and `invite--small`. I'll just rm invite files in the dist

**Review by akdetrick — APPROVED** [review]

**Pull request merged**
